### ISSUE TITLE
Ore Crusher Crashes Game

### ISSUE THREAD

**Issue by theshadowake** [phantamanta44/unclunkify#2]
Link to crash log: https://paste.dimdev.org/tumusokigo.mccrash

(Modpack = Awakening - Sky of Diamonds)

**Comment by phantamanta44** [comment]
i am currently having trouble replicating. can you provide more details on the conditions that cause this crash?

**Comment by ronw23** [comment]
When an Ore Crusher is placed into the world, it "becomes" a High Temp Furnace. When first interacting with this block, either nothing happens or the crash report from @theshadowake happens.

If this block is picked up, it shows up as a High Temp Furnace in inventory and can be placed back and used normally, as the furnace.

Tested in Forge 14.23.5.2838 with only this mod and dependency.

**Comment by phantamanta44** [comment]
issue was in libnine, fixed in https://github.com/phantamanta44/libnine/commit/d8b096ddf4a348bb19ad02e3498c3459d23a9356

**Comment by phantamanta44** [comment]
update to libnine 1.1.3 and y'all should be good
